(function () {
  'use strict';
  var C = window.FortyWeekCore, canvas = document.getElementById('status-canvas'), ctx = canvas.getContext('2d'), current = null;
  var keys = { profile:'youxiji.profile.v1', draft:'youxiji.draft.v1', records:'youxiji.records.v1' };
  var colors = { ink:'#17372B', forest:'#315A40', sage:'#7DA954', cream:'#FFF8E9', paperDeep:'#ECE3D2', gold:'#D3A14B', muted:'#708174' };
  var images = {}, names = ['leaf','sparkle','background','activity','appetite','diary','energy','sleep','body','mood'];
  names.forEach(function (name) { images[name] = new Image(); images[name].src = name === 'leaf' ? './assets/status/title-leaf.png' : name === 'sparkle' ? './assets/status/title-sparkle.png' : name === 'background' ? './assets/status/status-bg.png' : name === 'activity' ? './assets/activity.png' : name === 'appetite' ? './assets/appetite.png' : name === 'diary' ? './assets/diary.png' : './assets/status/' + name + '.png'; });
  function id(x) { return document.getElementById(x); }
  function value(x) { return (id(x).value || '').trim(); }
  function today() { return C.recordModel.displayDate(C.recordModel.today()); }
  function set(x,v) { id(x).value = v; }
  function font(size, weight, family) { return (weight || 500) + ' ' + size + 'px ' + (family || 'Source Han Sans CN, PingFang SC, sans-serif'); }
  function rr(x,y,w,h,r,fill,stroke,line) { ctx.beginPath(); ctx.moveTo(x+r,y); ctx.lineTo(x+w-r,y); ctx.quadraticCurveTo(x+w,y,x+w,y+r); ctx.lineTo(x+w,y+h-r); ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h); ctx.lineTo(x+r,y+h); ctx.quadraticCurveTo(x,y+h,x,y+h-r); ctx.lineTo(x,y+r); ctx.quadraticCurveTo(x,y,x+r,y); ctx.closePath(); if(fill){ctx.fillStyle=fill;ctx.fill();} if(stroke){ctx.lineWidth=line||2;ctx.strokeStyle=stroke;ctx.stroke();} }
  function text(s,x,y,o) { o=o||{}; ctx.save(); ctx.font=o.font||font(30);ctx.fillStyle=o.color||colors.ink;ctx.textAlign=o.align||'left';ctx.textBaseline=o.baseline||'alphabetic';ctx.fillText(s,x,y,o.maxWidth);ctx.restore(); }
  function icon(name,x,y,size,alpha) { var img=images[name];if(!img.complete||!img.naturalWidth)return;ctx.save();ctx.globalAlpha=alpha||1;ctx.imageSmoothingEnabled=false;ctx.drawImage(img,x,y,size,size);ctx.restore(); }
  function wrap(s,count) { var a=Array.from(s||''), lines=[];for(var i=0;i<a.length;i+=count)lines.push(a.slice(i,i+count).join(''));return lines.length?lines:['']; }
  function divider(y) { ctx.save();ctx.strokeStyle='rgba(49,90,64,.20)';ctx.lineWidth=2;ctx.setLineDash([3,9]);ctx.beginPath();ctx.moveTo(84,y);ctx.lineTo(940,y);ctx.stroke();ctx.restore();icon('sparkle',58,y-12,22,.75);icon('sparkle',944,y-12,22,.75); }
  function render(record) {
    var model=C.cardContent.buildCardModel(record), template=model.template;
    ctx.clearRect(0,0,1024,1536);if(images.background.complete&&images.background.naturalWidth)ctx.drawImage(images.background,0,0,1024,1536);else{ctx.fillStyle=colors.cream;ctx.fillRect(0,0,1024,1536);}
    icon('leaf',40,45,52,.78);text(model.shell.eyebrow,112,76,{font:font(28,500,'VT323, Courier New, monospace'),color:colors.forest});text(model.shell.title,512,160,{font:font(58,700),align:'center'});icon('sparkle',286,134,34,.9);icon('sparkle',704,134,34,.9);divider(252);
    rr(58,292,908,690,14,'rgba(255,253,245,.78)','rgba(211,161,75,.52)',3);
    var avatar=new Image();avatar.src='./assets/youxiji/'+model.shell.avatarId+'.png';avatar.onload=function(){ctx.save();ctx.imageSmoothingEnabled=false;ctx.beginPath();ctx.arc(128,376,40,0,Math.PI*2);ctx.clip();ctx.drawImage(avatar,25,0,180,170,88,336,80,80);ctx.restore();text(model.shell.nickname,186,378,{font:font(30,700)});};text('TODAY STATUS',92,326,{font:font(27,500,'VT323, Courier New, monospace'),color:colors.gold});text(model.shell.date+' · '+model.shell.week,930,332,{font:font(28,500,'VT323, Courier New, monospace'),color:colors.forest,align:'right'});text(template.heading,512,430,{font:font(32,700),align:'center'});
    template.rows.forEach(function(row,i){var y=500+i*76;if(i){ctx.strokeStyle='rgba(211,161,75,.34)';ctx.lineWidth=2;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(92,y-45);ctx.lineTo(932,y-45);ctx.stroke();ctx.setLineDash([]);}icon(row.icon,96,y-34,46,.92);text(row.label,162,y,{font:font(27,700)});if(row.key==='energy'){rr(352,y-18,410,26,6,colors.paperDeep);rr(352,y-18,Math.round(410*(C.statusOptions.energyProgress[row.value]||.5)),26,6,colors.sage);text(row.value,892,y+2,{font:font(26,700),align:'right'});}else{text(row.value,892,y,{font:font(row.key==='body'?22:25,500),align:'right'});}});
    divider(1000);text('TODAY I WANT TO KEEP',78,1058,{font:font(25,500,'VT323, Courier New, monospace'),color:colors.gold});rr(78,1084,868,286,12,'#FFFDF5','rgba(49,90,64,.25)',2);
    var moment=template.moment;if(moment){icon('sparkle',112,1120,24,.72);var titleLines=wrap(moment.title,22);titleLines.slice(0,2).forEach(function(line,i){text(line,160,1160+i*42,{font:font(31,700)});});if(moment.isFirst)text('第一次发现',160,1250,{font:font(21,700),color:'#B84D43'});if(moment.detail)wrap(moment.detail,28).slice(0,2).forEach(function(line,i){text(line,160,1290+i*32,{font:font(22,500),color:colors.muted});});}else{text('今天也值得被记住。',112,1190,{font:font(28,700)});}icon('diary',736,1134,174,.96);text('记录日期：'+model.shell.date,112,1350,{font:font(21,500),color:colors.muted});
    text('留住今天，等以后回头看看。',512,1422,{font:font(28,700),color:colors.forest,align:'center'});text(model.shell.brand,512,1495,{font:font(22,500,'VT323, Courier New, monospace'),color:colors.forest,align:'center'});
  }
  function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback;}catch(e){return fallback;}}
  function write(key,data){try{localStorage.setItem(key,JSON.stringify(data));return true;}catch(e){return false;}}
  function show(view){document.querySelectorAll('.view').forEach(function(el){el.hidden=el.dataset.view!==view;});window.scrollTo(0,0);}
  function fillOptions(key,list,selected){var el=id(key);el.innerHTML='';list.forEach(function(item){var option=document.createElement('option');option.value=item;option.textContent=item;option.selected=item===selected;el.appendChild(option);});}
  function week(prefix){return {weeks:Number(value(prefix+'-week-major')),days:Number(value(prefix+'-week-minor'))};}
  function setProfile(profile){id('home-avatar').src='./assets/youxiji/'+profile.avatarId+'.png';id('home-avatar').style.objectFit='cover';id('home-avatar').style.objectPosition='50% 0';id('home-nickname').textContent=profile.nickname;id('home-week').textContent='当前孕周 · W'+profile.week.weeks+'+'+profile.week.days;var marker=document.querySelector('.route-visual b');if(marker)marker.textContent='现在 · W'+profile.week.weeks+'+'+profile.week.days;id('setup-nickname').value=profile.nickname;id('setup-nickname-count').textContent=C.recordModel.charLength(profile.nickname);set('setup-week-major',profile.week.weeks);set('setup-week-minor',profile.week.days);document.querySelectorAll('.avatar-choice').forEach(function(a){a.classList.toggle('selected',a.dataset.avatar===profile.avatarId);});}
  function setupProfile(){var nickname=value('setup-nickname'),profile={nickname:nickname,avatarId:(document.querySelector('.avatar-choice.selected')||{}).dataset&&document.querySelector('.avatar-choice.selected').dataset.avatar||'avatar-01',week:week('setup')};if(!nickname||C.recordModel.charLength(nickname)>C.recordValidation.max.nickname||!C.recordModel.isValidWeek(profile.week)){id('setup-error').textContent='请填写昵称，并选择正确的孕周。';return;}write(keys.profile,profile);C.analytics.track('record_start');setProfile(profile);show('home');}
  function buildRecord(){var profile=read(keys.profile,{}), moment={title:value('moment-title'),detail:value('moment-detail'),isFirst:id('moment-first').checked};var source={type:'daily_log',actualDate:value('record-date'),gestationalWeek:week('record'),profile:profile,status:{energy:value('record-energy'),sleep:value('record-sleep'),body:value('record-body'),appetite:value('record-appetite'),activity:value('record-activity'),mood:value('record-mood')},moments:(moment.title||moment.detail||moment.isFirst)?[moment]:[]};return C.recordModel.createRecord(source);}
  function saveDraft(){var r=buildRecord();write(keys.draft,r);}
  function loadRecordForm(){var p=read(keys.profile,{}),d=read(keys.draft,null)||{};set('record-date',d.actualDate?C.recordModel.displayDate(d.actualDate):today());var w=d.gestationalWeek||p.week||{weeks:5,days:0};set('record-week-major',w.weeks);set('record-week-minor',w.days);var st=d.status||{};['energy','sleep','body','appetite','activity','mood'].forEach(function(k){if(id('record-'+k))id('record-'+k).value=st[k]||id('record-'+k).value;});var m=d.moments&&d.moments[0]||{};set('moment-title',m.title||'');set('moment-detail',m.detail||'');id('moment-first').checked=m.isFirst===true;updateCounts();}
  function updateCounts(){[['setup-nickname','setup-nickname-count'],['moment-title','moment-title-count'],['moment-detail','moment-detail-count']].forEach(function(pair){id(pair[1]).textContent=C.recordModel.charLength(id(pair[0]).value);});}
  function showResult(record){current=record;write(keys.draft,null);var records=read(keys.records,[]);records.push(record);write(keys.records,records.slice(-20));render(record);id('generated-image').hidden=true;id('download-status').textContent='';var xhs=window.FortyWeekPlatform&&window.FortyWeekPlatform.xhs, post=id('post-button');post.hidden=!xhs||!xhs.available();id('result-platform-note').textContent=post.hidden?'小红书内打开时，可直接发布到小红书。':'';show('result');C.analytics.track('card_generate_success');}
  var submitting = false;
  function submit(e){e.preventDefault();if(submitting)return;var record=buildRecord(),check=C.recordValidation.validateRecord(record,false);id('record-error').textContent=check.valid?'':check.errors[0];if(!check.valid){saveDraft();return;}submitting=true;C.analytics.track('record_form_valid');showResult(record);setTimeout(function(){submitting=false;},300);}
  function imageData(){return canvas.toDataURL('image/png');}
  function showImage(data,message){id('generated-image').src=data;id('generated-image').hidden=false;id('download-status').textContent=message;var modal=id('image-modal');if(!modal){modal=document.createElement('div');modal.id='image-modal';modal.innerHTML='<div class="image-modal-card"><button type="button" class="image-modal-close" aria-label="关闭预览">×</button><p>记录卡已生成</p><img alt="生成的有喜记记录卡"><small>长按图片即可保存到手机</small></div>';modal.style.cssText='position:fixed;z-index:20;inset:0;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(23,55,43,.72);';modal.querySelector('.image-modal-card').style.cssText='position:relative;max-height:94vh;max-width:520px;padding:14px;background:#fff8e9;border-radius:10px;text-align:center;box-shadow:0 16px 40px rgba(0,0,0,.25);';modal.querySelector('img').style.cssText='display:block;max-width:100%;max-height:78vh;width:auto;height:auto;margin:8px auto;';modal.querySelector('p').style.cssText='margin:0;color:#315a40;font-weight:700;';modal.querySelector('small').style.cssText='color:#708174;';modal.querySelector('.image-modal-close').style.cssText='position:absolute;right:8px;top:4px;border:0;background:none;color:#315a40;font-size:28px;';modal.querySelector('.image-modal-close').addEventListener('click',function(){modal.hidden=true;});document.body.appendChild(modal);}modal.querySelector('img').src=data;modal.hidden=false;}
  function saveImage(){var data=imageData(),xhs=window.FortyWeekPlatform&&window.FortyWeekPlatform.xhs;id('download-button').disabled=true;if(xhs&&xhs.available()&&xhs.saveImage){xhs.saveImage(data).then(function(){id('download-status').textContent='记录卡已保存到相册。';C.analytics.track('image_save_success');}).catch(function(){showImage(data,'保存权限未开启，可长按下方图片保存。');C.analytics.track('image_save_fail');}).then(function(){id('download-button').disabled=false;});}else{showImage(data,'图片已生成，长按图片即可保存。');C.analytics.track('image_save_success');id('download-button').disabled=false;}}
  function postImage(){var xhs=window.FortyWeekPlatform&&window.FortyWeekPlatform.xhs;if(!xhs||!xhs.available()){id('download-status').textContent='当前不是小红书小工具环境。';return;}var button=id('post-button');button.disabled=true;id('download-status').textContent='正在打开小红书发布页……';C.analytics.track('post_note_click');xhs.postCard(current,imageData()).then(function(){id('download-status').textContent='已打开小红书发布页，请确认后发布。';C.analytics.track('post_note_invoke_success');}).catch(function(){id('download-status').textContent='发布失败，请保存图片后重试。';C.analytics.track('post_note_invoke_fail');}).then(function(){button.disabled=false;});}
  function initAvatars(){var grid=id('avatar-grid');for(var i=1;i<=8;i++){var b=document.createElement('button');b.type='button';b.className='avatar-choice'+(i===1?' selected':'');b.dataset.avatar='avatar-0'+i;b.innerHTML='<img src="./assets/youxiji/avatar-0'+i+'.png" alt="头像 '+i+'">';b.addEventListener('click',function(){document.querySelectorAll('.avatar-choice').forEach(function(a){a.classList.remove('selected');});this.classList.add('selected');});grid.appendChild(b);}}
  fillOptions('record-energy',C.statusOptions.energy,'还可以');fillOptions('record-sleep',C.statusOptions.sleep,'睡得不错');fillOptions('record-appetite',C.statusOptions.appetite,'一般');fillOptions('record-activity',C.statusOptions.activity,'日常活动');fillOptions('record-mood',C.statusOptions.mood,'平稳');initAvatars();set('record-date',today());
  id('setup-form').addEventListener('submit',function(e){e.preventDefault();setupProfile();});id('record-today').addEventListener('click',function(){C.analytics.track('record_start');loadRecordForm();show('record');});id('record-form').addEventListener('submit',submit);id('edit-profile').addEventListener('click',function(){var p=read(keys.profile,{});setProfile(p);show('welcome');});document.querySelectorAll('[data-back]').forEach(function(b){b.addEventListener('click',function(){C.analytics.track('return_open');show(b.dataset.back);});});id('download-button').addEventListener('click',saveImage);id('post-button').addEventListener('click',postImage);['setup-nickname','moment-title','moment-detail'].forEach(function(k){id(k).addEventListener('input',function(){updateCounts();if(k!=='setup-nickname')saveDraft();});});['record-date','record-week-major','record-week-minor','record-body'].forEach(function(k){id(k).addEventListener('input',saveDraft);});['record-energy','record-sleep','record-appetite','record-activity','record-mood','moment-first'].forEach(function(k){id(k).addEventListener('change',saveDraft);});Object.keys(images).forEach(function(k){images[k].onload=function(){if(current)render(current);};});
  var profile=read(keys.profile,null);if(profile){setProfile(profile);show('home');}else{show('welcome');}C.analytics.track('app_open');
}());
