(function () {
  'use strict';
  var homeStyles = document.createElement('link'); homeStyles.rel = 'stylesheet'; homeStyles.href = './home.css'; document.head.appendChild(homeStyles); document.querySelector('.scene-bg').src = './assets/home/journey-scene.png';
  var C = window.FortyWeekCore, canvas = document.getElementById('status-canvas'), ctx = canvas.getContext('2d'), current = null;
  var keys = { profile:'youxiji.profile.v1', draft:'youxiji.draft.v1', records:'youxiji.records.v1' }, storageNotice='🔒 本工具无需登录，记录只保存在当前设备。<br>更换设备或清除浏览器数据后，记录不会同步，生成后请及时保存图片。';
  var colors = { ink:'#17372B', forest:'#315A40', sage:'#7DA954', cream:'#FFF8E9', paperDeep:'#ECE3D2', gold:'#D3A14B', muted:'#708174' };
  var images = {}, names = ['leaf','sparkle','firstSparkle','background','activity','appetite','diary','energy','sleep','body','mood'];
  names.forEach(function (name) { images[name] = new Image(); images[name].src = name === 'leaf' ? './assets/status/title-leaf.png' : name === 'sparkle' ? './assets/status/title-sparkle.png' : name === 'firstSparkle' ? './assets/status/star0.png' : name === 'background' ? './assets/status/status-bg.png' : name === 'activity' ? './assets/activity.png' : name === 'appetite' ? './assets/appetite.png' : name === 'diary' ? './assets/diary.png' : './assets/status/' + name + '.png'; });
  images.logo = new Image(); images.logo.src = './assets/home/logo.png'; images.journeyScene = new Image(); images.journeyScene.src = './assets/home/journey-scene.png';
  function id(x) { return document.getElementById(x); }
  function value(x) { return (id(x).value || '').trim(); }
  function today() { return C.recordModel.displayDate(C.recordModel.today()); }
  function set(x,v) { id(x).value = v; }
  function font(size, weight, family) { return (weight || 500) + ' ' + size + 'px ' + (family || 'Source Han Sans CN, PingFang SC, sans-serif'); }
  function rr(x,y,w,h,r,fill,stroke,line) { ctx.beginPath(); ctx.moveTo(x+r,y); ctx.lineTo(x+w-r,y); ctx.quadraticCurveTo(x+w,y,x+w,y+r); ctx.lineTo(x+w,y+h-r); ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h); ctx.lineTo(x+r,y+h); ctx.quadraticCurveTo(x,y+h,x,y+h-r); ctx.lineTo(x,y+r); ctx.quadraticCurveTo(x,y,x+r,y); ctx.closePath(); if(fill){ctx.fillStyle=fill;ctx.fill();} if(stroke){ctx.lineWidth=line||2;ctx.strokeStyle=stroke;ctx.stroke();} }
  function text(s,x,y,o) { o=o||{}; ctx.save(); ctx.font=o.font||font(30);ctx.fillStyle=o.color||colors.ink;ctx.textAlign=o.align||'left';ctx.textBaseline=o.baseline||'alphabetic';ctx.fillText(s,x,y,o.maxWidth);ctx.restore(); }
  function icon(name,x,y,size,alpha) { var img=images[name];if(!img.complete||!img.naturalWidth)return;ctx.save();ctx.globalAlpha=alpha||1;ctx.imageSmoothingEnabled=false;ctx.drawImage(img,x,y,size,size);ctx.restore(); }
  function wrap(s,count) { var a=Array.from(s||''), lines=[];for(var i=0;i<a.length;i+=count)lines.push(a.slice(i,i+count).join(''));return lines.length?lines:['']; }
  function wrapByWidth(s,maxWidth,style) { var chars=Array.from(s||''),lines=[],line='';ctx.save();ctx.font=style;chars.forEach(function(ch){var next=line+ch;if(line&&ctx.measureText(next).width>maxWidth){lines.push(line);line=ch;}else line=next;});if(line||!lines.length)lines.push(line);ctx.restore();return lines; }
  function divider(y) { ctx.save();ctx.strokeStyle='rgba(49,90,64,.20)';ctx.lineWidth=2;ctx.setLineDash([3,9]);ctx.beginPath();ctx.moveTo(84,y);ctx.lineTo(940,y);ctx.stroke();ctx.restore();icon('sparkle',58,y-12,22,.75);icon('sparkle',944,y-12,22,.75); }
  function render(record) {
    var model=C.cardContent.buildCardModel(record), template=model.template, status=template.rows, moment=template.moment;
    var firstMoment=moment&&moment.isFirst, titleX=firstMoment?152:104, titleWidth=firstMoment?768:816, titleLines=moment?wrapByWidth(moment.title,titleWidth,font(39,700)):['今天也值得被记住。'];
    var detailLines=moment&&moment.detail?wrapByWidth(moment.detail,816,font(28,500)):[];
    var statusTop=470,statusBottom=914,momentTop=statusBottom+24;
    var titleY=moment?momentTop+130:momentTop+150, detailY=titleY+titleLines.length*54+48;
    var momentBottom=moment?(detailLines.length?detailY+detailLines.length*44+30:titleY+titleLines.length*54+30):titleY+38;
    var momentHeight=Math.max(190,momentBottom-momentTop), sceneTop=momentBottom+48, sceneWidth=1024;
    var sceneHeight=Math.round(sceneWidth*768/2048), canvasHeight=sceneTop+sceneHeight+24;
    canvas.height=canvasHeight;ctx.clearRect(0,0,1024,canvasHeight);ctx.fillStyle=colors.cream;ctx.fillRect(0,0,1024,canvasHeight);
    if(images.logo.complete&&images.logo.naturalWidth){ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(images.logo,417,18,190,166);ctx.restore();}
    var heading=model.shell.nickname+'的今日记录',headingSize=58,headingFont=font(headingSize,700),headingWidth;ctx.save();ctx.font=headingFont;headingWidth=ctx.measureText(heading).width;ctx.restore();while(headingWidth>700&&headingSize>42){headingSize-=2;headingFont=font(headingSize,700);ctx.save();ctx.font=headingFont;headingWidth=ctx.measureText(heading).width;ctx.restore();}text(heading,512,274,{font:headingFont,align:'center',maxWidth:700});var headingLeft=Math.max(42,512-headingWidth/2-58),headingRight=Math.min(982,512+headingWidth/2+24);icon('sparkle',headingLeft,245,34,.9);icon('sparkle',headingRight,245,34,.9);
    rr(232,312,560,88,44,'rgba(255,253,245,.9)','rgba(49,90,64,.28)',2);text(model.shell.date+'   ·   '+model.shell.week,512,369,{font:font(48,500,'VT323, Courier New, monospace'),align:'center'});divider(430);
    rr(62,statusTop,900,statusBottom-statusTop,18,'rgba(255,253,245,.88)','rgba(211,161,75,.72)',3);text('TODAY’S LOG',106,522,{font:font(29,500,'VT323, Courier New, monospace'),color:colors.gold});
    var energy=status[0];icon(energy.icon,106,552,50,.95);text(energy.label,168,596,{font:font(29,700)});rr(310,573,390,28,7,colors.paperDeep);rr(310,573,Math.round(390*(C.statusOptions.energyProgress[energy.value]||.5)),28,7,colors.sage);text(energy.value,892,597,{font:font(28,700),align:'right'});
    var pairs=[[status[1],status[3]],[status[4],status[5]]];pairs.forEach(function(pair,row){var y=690+row*94;ctx.strokeStyle='rgba(211,161,75,.30)';ctx.lineWidth=2;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(104,y-50);ctx.lineTo(920,y-50);ctx.stroke();ctx.setLineDash([]);pair.forEach(function(item,col){var x=col?520:106;icon(item.icon,x,y-32,45,.95);text(item.label,x+62,y+3,{font:font(27,700)});text(item.value,x+350,y+3,{font:font(24,500),align:'right'});});});
    var body=status[2];rr(86,832,852,58,12,'rgba(238,243,220,.7)','rgba(125,169,84,.30)',2);icon(body.icon,108,841,40,.95);text(body.label,166,869,{font:font(25,700)});text(body.value,900,869,{font:font(23,500),align:'right',maxWidth:700});
    rr(62,momentTop,900,momentHeight,18,'rgba(255,253,245,.9)','rgba(211,161,75,.72)',3);text('✦  今天留下的瞬间  ✦',512,momentTop+46,{font:font(28,700),align:'center',color:colors.gold});
    if(moment){if(firstMoment)icon('firstSparkle',104,titleY-42,42,.95);titleLines.forEach(function(line,i){text(line,titleX,titleY+i*54,{font:font(39,700),maxWidth:titleWidth});});detailLines.forEach(function(line,i){text(line,104,detailY+i*44,{font:font(28,500),color:colors.ink,maxWidth:816});});}else{text('今天也值得被记住。',104,titleY,{font:font(32,700)});}
    if(images.journeyScene.complete&&images.journeyScene.naturalWidth){ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(images.journeyScene,0,sceneTop,sceneWidth,sceneHeight);ctx.restore();}var avatar=new Image();avatar.src='./assets/youxiji/'+model.shell.avatarId+'.png';avatar.onload=function(){var avatarWidth=48,avatarHeight=Math.round(avatarWidth*avatar.naturalHeight/avatar.naturalWidth),roadAvatarY=sceneTop+sceneHeight-150;ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(avatar,0,0,avatar.naturalWidth,avatar.naturalHeight,690,roadAvatarY,avatarWidth,avatarHeight);ctx.restore();};
  }
  function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback;}catch(e){return fallback;}}
  function write(key,data){try{localStorage.setItem(key,JSON.stringify(data));return true;}catch(e){return false;}}
  function show(view){document.querySelectorAll('.view').forEach(function(el){el.hidden=el.dataset.view!==view;});window.scrollTo(0,0);}
  function fillOptions(key,list,selected){var el=id(key);el.innerHTML='';list.forEach(function(item){var option=document.createElement('option');option.value=item;option.textContent=item;option.selected=item===selected;el.appendChild(option);});}
  function week(prefix){return {weeks:Number(value(prefix+'-week-major')),days:Number(value(prefix+'-week-minor'))};}
  function setProfile(profile){id('home-avatar').src='./assets/youxiji/'+profile.avatarId+'.png';id('home-avatar').style.objectFit='cover';id('home-avatar').style.objectPosition='50% 0';id('journey-avatar').src='./assets/youxiji/'+profile.avatarId+'.png';id('home-nickname').textContent=profile.nickname;var weekText='W'+profile.week.weeks+'+'+profile.week.days;id('home-week').textContent='当前孕周 · '+weekText;id('journey-week').textContent=weekText;var progress=Math.max(0,Math.min(100,(profile.week.weeks*7+profile.week.days)/280*100));document.querySelector('.route-progress').style.width=progress+'%';id('journey-node').style.left=progress+'%';document.querySelector('.route-track em').style.left='calc('+progress+'% - 12px)';id('setup-nickname').value=profile.nickname;id('setup-nickname-count').textContent=C.recordModel.charLength(profile.nickname);set('setup-week-major',profile.week.weeks);set('setup-week-minor',profile.week.days);document.querySelectorAll('.avatar-choice').forEach(function(a){a.classList.toggle('selected',a.dataset.avatar===profile.avatarId);});}
  function setupProfile(){var nickname=value('setup-nickname'),profile={nickname:nickname,avatarId:(document.querySelector('.avatar-choice.selected')||{}).dataset&&document.querySelector('.avatar-choice.selected').dataset.avatar||'avatar-01',week:week('setup')};if(!nickname||C.recordModel.charLength(nickname)>C.recordValidation.max.nickname||!C.recordModel.isValidWeek(profile.week)){id('setup-error').textContent='请填写昵称，并选择正确的孕周。';return;}write(keys.profile,profile);C.analytics.track('record_start');setProfile(profile);show('home');}
  function buildRecord(){var profile=read(keys.profile,{}), moment={title:value('moment-title'),detail:value('moment-detail'),isFirst:id('moment-first').checked};var source={type:'daily_log',actualDate:value('record-date'),gestationalWeek:week('record'),profile:profile,status:{energy:value('record-energy'),sleep:value('record-sleep'),body:value('record-body'),appetite:value('record-appetite'),activity:value('record-activity'),mood:value('record-mood')},moments:(moment.title||moment.detail||moment.isFirst)?[moment]:[]};return C.recordModel.createRecord(source);}
  function updateTodayState(){var records=read(keys.records,[]),today=C.recordModel.today(),record=records.filter(function(item){return item&&C.recordModel.normalizeDate(item.actualDate)===today;}).pop(),state=id('today-state'),title=document.querySelector('.today-card>h3'),description=document.querySelector('.today-card>p');if(record){state.textContent='✓ 今日已记录';title.textContent='今天已经留下记录';description.textContent='今天的状态与瞬间已经显示在你的记录卡里。';}else{state.textContent='○ 尚未记录';title.textContent='今天还没有留下记录';description.textContent='记录之后，今天的状态与瞬间会显示在这里。';}}
  function saveDraft(){var r=buildRecord();write(keys.draft,r);}
  function loadRecordForm(){var p=read(keys.profile,{}),d=read(keys.draft,null)||{};set('record-date',d.actualDate?C.recordModel.displayDate(d.actualDate):today());var w=d.gestationalWeek||p.week||{weeks:5,days:0};set('record-week-major',w.weeks);set('record-week-minor',w.days);var st=d.status||{};['energy','sleep','body','appetite','activity','mood'].forEach(function(k){if(id('record-'+k))id('record-'+k).value=st[k]||id('record-'+k).value;});var m=d.moments&&d.moments[0]||{};set('moment-title',m.title||'');set('moment-detail',m.detail||'');id('moment-first').checked=m.isFirst===true;updateCounts();}
  function updateCounts(){[['setup-nickname','setup-nickname-count'],['moment-title','moment-title-count'],['moment-detail','moment-detail-count']].forEach(function(pair){id(pair[1]).textContent=C.recordModel.charLength(id(pair[0]).value);});}
  function showResult(record){current=record;write(keys.draft,null);var records=read(keys.records,[]);records.push(record);write(keys.records,records.slice(-20));updateTodayState();render(record);id('generated-image').hidden=true;id('download-status').textContent='';document.querySelector('.preview-hint').textContent='记录只保存在当前设备，生成后请及时保存图片。';var xhs=window.FortyWeekPlatform&&window.FortyWeekPlatform.xhs, post=id('post-button');post.hidden=!xhs||!xhs.available();id('result-platform-note').textContent=post.hidden?'小红书内打开时，可直接发布到小红书。':'';show('result');C.analytics.track('card_generate_success');}
  var submitting = false;
  function submit(e){e.preventDefault();if(submitting)return;var record=buildRecord(),check=C.recordValidation.validateRecord(record,false);id('record-error').textContent=check.valid?'':check.errors[0];if(!check.valid){saveDraft();return;}submitting=true;C.analytics.track('record_form_valid');showResult(record);setTimeout(function(){submitting=false;},300);}
  function imageData(){return canvas.toDataURL('image/png');}
  function showImage(data,message){id('generated-image').src=data;id('generated-image').hidden=false;id('download-status').textContent=message;var modal=id('image-modal');if(!modal){modal=document.createElement('div');modal.id='image-modal';modal.innerHTML='<div class="image-modal-card"><button type="button" class="image-modal-close" aria-label="关闭预览">×</button><p>记录卡已生成</p><img alt="生成的有喜记记录卡"><small>长按图片即可保存到手机</small></div>';modal.style.cssText='position:fixed;z-index:20;inset:0;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(23,55,43,.72);';modal.querySelector('.image-modal-card').style.cssText='position:relative;max-height:94vh;max-width:520px;padding:14px;background:#fff8e9;border-radius:10px;text-align:center;box-shadow:0 16px 40px rgba(0,0,0,.25);';modal.querySelector('img').style.cssText='display:block;max-width:100%;max-height:78vh;width:auto;height:auto;margin:8px auto;';modal.querySelector('p').style.cssText='margin:0;color:#315a40;font-weight:700;';modal.querySelector('small').style.cssText='color:#708174;';modal.querySelector('.image-modal-close').style.cssText='position:absolute;right:8px;top:4px;border:0;background:none;color:#315a40;font-size:28px;';var closeModal=function(){modal.hidden=true;modal.style.display='none';};modal.querySelector('.image-modal-close').addEventListener('click',closeModal);modal.addEventListener('click',function(e){if(e.target===modal)closeModal();});document.body.appendChild(modal);}modal.querySelector('img').src=data;modal.hidden=false;modal.style.display='flex';}
  function saveImage(){var data=imageData(),xhs=window.FortyWeekPlatform&&window.FortyWeekPlatform.xhs;id('download-button').disabled=true;if(xhs&&xhs.available()&&xhs.saveImage){xhs.saveImage(data).then(function(){id('download-status').textContent='记录卡已保存到相册。';C.analytics.track('image_save_success');}).catch(function(){showImage(data,'保存权限未开启，可长按下方图片保存。');C.analytics.track('image_save_fail');}).then(function(){id('download-button').disabled=false;});}else{showImage(data,'图片已生成，长按图片即可保存。');C.analytics.track('image_save_success');id('download-button').disabled=false;}}
  function postImage(){var xhs=window.FortyWeekPlatform&&window.FortyWeekPlatform.xhs;if(!xhs||!xhs.available()){id('download-status').textContent='当前不是小红书小工具环境。';return;}var button=id('post-button');button.disabled=true;id('download-status').textContent='正在打开小红书发布页……';C.analytics.track('post_note_click');xhs.postCard(current,imageData()).then(function(){id('download-status').textContent='已打开小红书发布页，请确认后发布。';C.analytics.track('post_note_invoke_success');}).catch(function(){id('download-status').textContent='发布失败，请保存图片后重试。';C.analytics.track('post_note_invoke_fail');}).then(function(){button.disabled=false;});}
  function initAvatars(){var grid=id('avatar-grid');for(var i=1;i<=8;i++){var b=document.createElement('button');b.type='button';b.className='avatar-choice'+(i===1?' selected':'');b.dataset.avatar='avatar-0'+i;b.innerHTML='<img src="./assets/youxiji/avatar-0'+i+'.png" alt="头像 '+i+'">';b.addEventListener('click',function(){document.querySelectorAll('.avatar-choice').forEach(function(a){a.classList.remove('selected');});this.classList.add('selected');});grid.appendChild(b);}}
  fillOptions('record-energy',C.statusOptions.energy,'还可以');fillOptions('record-sleep',C.statusOptions.sleep,'睡得不错');fillOptions('record-appetite',C.statusOptions.appetite,'一般');fillOptions('record-activity',C.statusOptions.activity,'日常活动');fillOptions('record-mood',C.statusOptions.mood,'平稳');initAvatars();set('record-date',today());
  id('setup-form').addEventListener('submit',function(e){e.preventDefault();setupProfile();});id('record-today').addEventListener('click',function(){C.analytics.track('record_start');loadRecordForm();show('record');});id('record-form').addEventListener('submit',submit);id('edit-profile').addEventListener('click',function(){var p=read(keys.profile,{});setProfile(p);show('welcome');});document.querySelectorAll('[data-back]').forEach(function(b){b.addEventListener('click',function(){C.analytics.track('return_open');show(b.dataset.back);});});id('download-button').addEventListener('click',saveImage);id('post-button').addEventListener('click',postImage);['setup-nickname','moment-title','moment-detail'].forEach(function(k){id(k).addEventListener('input',function(){updateCounts();if(k!=='setup-nickname')saveDraft();});});['record-date','record-week-major','record-week-minor','record-body'].forEach(function(k){id(k).addEventListener('input',saveDraft);});['record-energy','record-sleep','record-appetite','record-activity','record-mood','moment-first'].forEach(function(k){id(k).addEventListener('change',saveDraft);});Object.keys(images).forEach(function(k){images[k].onload=function(){if(current)render(current);};});
  document.querySelector('.privacy-note').innerHTML=storageNotice;var profile=read(keys.profile,null);if(profile){setProfile(profile);updateTodayState();show('home');}else{show('welcome');}C.analytics.track('app_open');
}());
